# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChatApp
pod ‘Firebase/Firestore'
pod 'FirebaseStorage'
pod 'FirebaseCore'
pod 'FirebaseFirestore'
pod 'SDWebImage'
pod 'Firebase/Auth'
pod 'FBSDKLoginKit'
pod 'FacebookLogin'
pod 'ZaloSDK'
pod 'GoogleSignIn', '6.0.2'
pod 'RxSwift', '6.5.0'
pod 'RxCocoa', '6.5.0'
pod 'SnapKit'
pod 'SwiftGen', '~> 6.0'
pod 'RxSwiftExt/Core'
pod 'SwiftyJSON'
pod 'Toaster'
pod 'IQKeyboardManagerSwift', '6.3.0'
pod 'TTGTagCollectionView','~> 2.4.2'
end
