# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChatApp
pod ‘Firebase/Firestore'
pod 'FirebaseStorage'
pod 'FirebaseCore'
pod 'FirebaseFirestore'
pod 'SDWebImage'
pod 'Firebase/Auth'
pod 'FBSDKLoginKit'
pod 'FacebookLogin'
pod 'ZaloSDK'
pod 'GoogleSignIn'
# pod 'RxSwift', '6.5.0'
# pod 'RxCocoa', '6.5.0'
end
